server:
  port: 8087
  servlet:
    context-path: /api/v1
spring:
  datasource:
    port: 5115
    url: jdbc:postgresql://localhost:1211/postgres
    username: postgres
    password: 3651551a
  jpa:
    hibernate:
      ddl-auto: update

hotDesk:
  security:
    jwt-secret: kvR0X68rIEaDGvIQKnhPULJYqOw3Sms4
